apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  {{ include "truststoremgr.labels" . | nindent 4 }}
  name: {{ include "truststoremgr.roleName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - truststore-mgr.ibm.com
  resources:
  - truststores
  - truststores/status
  - truststores/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
