apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  {{ include "truststoremgr.labels" . | nindent 4 }}
  name: {{ include "truststoremgr.roleBindingName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "truststoremgr.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "truststoremgr.serviceAccountName" . }}
